# Generated by Django 2.2 on 2020-07-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=255)),
                ('director_name', models.CharField(max_length=255)),
                ('popularity', models.IntegerField()),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('imdb_score', models.IntegerField()),
                ('trailer_url', models.CharField(max_length=255)),
                ('genre', models.ManyToManyField(to='movies.Genre')),
            ],
        ),
    ]
