# Generated by Django 2.2 on 2020-07-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=250)),
                ('director_name', models.CharField(max_length=250)),
                ('popularity', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('gener', models.CharField(max_length=250)),
                ('imdb_score', models.IntegerField()),
            ],
        ),
    ]
