# Generated by Django 2.2 on 2020-07-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='image',
            field=models.FileField(upload_to='movie_images/'),
        ),
    ]
