# Generated by Django 2.2 on 2020-07-12 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200712_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='gener',
            new_name='genre',
        ),
    ]
