# Generated by Django 2.2 on 2020-07-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20200713_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
