# Generated by Django 2.2 on 2020-07-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20200713_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='image',
            field=models.FileField(default=None, upload_to='images/'),
        ),
    ]
